title: Baby With a Blow Torch
author: Hadley
email: fake@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Bleep, bloop.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
